services:
  - type: web
    name: inteliview-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        value: https://inteli-view.vercel.app
      - key: PORT
        value: 3000 